CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fist_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    number TEXT NOT NULL,
    apartment_num TEXT,
    street_name TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    verified BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO users
(fist_name, last_name, email, mobile_number, number, street_name, city, state, zip_code)
VALUES
('Jason', 'Carcamo', 'jasoncarcamo30@yahoo.com', '631-703-0168', '11', 'Rodney pl', 'Amityville', 'Ny', '11701');